### ISSUE TITLE
Support for Canada

### ISSUE THREAD

**Issue by brandonb927** [staringispolite/wtfjht-alexa-skill#2]
I got an Echo device over the recent holidays and I would love to continue following WTFJHT in audio form on it. It appears that the Alexa skill is not available in Canada. Any plans to add the locale for it? I'm not entirely sure how to add it myself so I might submit a PR if I can do that.

![image](https://user-images.githubusercontent.com/1509352/34499732-3f05a0bc-efbc-11e7-9f6c-b6e0c84afdec.png)

**Comment by staringispolite** [comment]
That annoying, and sorry to hear about this. They claimed to us in developer email that they automatically supported every English speaking locale, and that they would roll it out without any developer intervention needed, some time last year.

Unfortunately I believe this is a setting in the developer console, not the code. I'll take another look, it's possible this changed on us without notice.

**Comment by staringispolite** [comment]
![image](https://user-images.githubusercontent.com/151620/34500160-680e04b6-efbe-11e7-8e18-8075492e103f.png)

Hm. Just confirmed in the developer portal and the skill store (see screenshot) that there's a Canada locale available. Maybe this was a temporary glitch? Or perhaps something on your end is causing them to mis-identify your location?

**Comment by brandonb927** [comment]
Oof I feel embarrassed now. I had clicked on the `Enable Skill` [here](http://wtfalexa.com/) and was taken to amazon.com and not amazon.ca 🤦 The skill in fact is available on [amazon.ca](https://www.amazon.ca/Now-or-Never-Happened-Today/dp/B06XWJSK86/).

**Comment by staringispolite** [comment]
Ahhh well glad to hear it's working!
